### ISSUE TITLE
A problem about the relationship between 320*240 image and 17*17 patches .

### ISSUE THREAD

**Issue by xinqingbuhao** [gdahia/high-res-fingerprint-recognition#3]
the training process use 17x17 patches  as input of the net ？then the result is pred of this patche. But the inference process use 320*240 images to get a pore map ,then use NMS to refine the pore map. i can't understand this point . thx.

**Comment by gdahia** [comment]
As specified in the pore detection [paper](https://arxiv.org/abs/1811.06846), we train with 17x17 patches to decorrelate the data, but infer in whole images because it is faster. Reading the paper should enlighten this topic. Pore detection in this repository is discontinued. Please refer to https://github.com/gdahia/fingerprint-pore-detection instead for further information. I am closing this issue, if you have further problems, please open another issue in the other repository.
